CONSUMER_KEY = "CONSUMER KEY HERE"
CONSUMER_SECRET = "CONSUMER SECRET HERE"
ACCESS_TOKEN = "ACCESS TOKEN HERE"
ACCESS_TOKEN_SECRET= "ACCESS TOKEN SECRET HERE"
BEARER_TOKEN = "BEARER TOKEN HERE"

DATA_PATH = "DATA FOLDER PATH HERE"
